# Generated by Django 3.2.5 on 2021-11-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Phone_Number',
            field=models.CharField(max_length=15),
        ),
    ]
