# Generated by Django 3.2.5 on 2021-11-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20211114_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
